site_name: DRF Blog Bridger (WIP)

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - API Reference : 'api_docs.md'
  
  # tutorial section
  - Tutorials:
    # - guides/Getting-Started.md
    - Customizations: 'guides/customizations.md'

theme:
  name: material
  icon:
    - annotation: material/arrow-right-circle
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.tooltips


  palette:
  # toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

      # toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences

site_url: https://drf-blog-bridger.readthedocs.io